//------------------------------------------------------------------------------
// <auto-generated>
//     Bu kod araç tarafından oluşturuldu.
//
//     Bu dosyada yapılacak değişiklikler yanlış davranışa neden olabilir ve
//     kod yeniden üretildiğinde kaybolur.
// </auto-generated>
//------------------------------------------------------------------------------

namespace admin
{


    public partial class About
    {
    }
}
